# Substitui pelo teu Número e Nome (Ex: 122985 - Ivo Gaspar)
name: Qodana - Deteção de God Class

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2023.3
        with:
          args: --fail-threshold,0
