name: SonarCloud Quality Gate Check

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow desativado
        run: echo "SonarCloud workflow desativado temporariamente"
